### ISSUE TITLE
ZlpDirectoryInfo.Name is empty when dir path has trailing slash

### ISSUE THREAD

**Issue by KimikoMuffin** [UweKeim/ZetaLongPaths#15]
As the title says:

```C#
ZlpDirectoryInfo dirInfo1 = new ZlpDirectoryInfo(@"C:\Foo\Bar");
Console.WriteLine(dirInfo1.Name); //"Bar"
ZlpDirectoryInfo dirInfo2 = new ZlpDirectoryInfo(@"C:\Foo\Bar\");
Console.WriteLine(dirInfo2.Name); //"", an empty string
```

**Comment by UweKeim** [comment]
I've just did a test:

```csharp
var dirInfo1 = new ZlpDirectoryInfo(@"C:\Foo\Bar");
Console.WriteLine(dirInfo1.Name); //"Bar"
var dirInfo2 = new ZlpDirectoryInfo(@"C:\Foo\Bar\");
Console.WriteLine(dirInfo2.Name); //"", an empty string

var dirInfo3 = new DirectoryInfo(@"C:\Foo\Bar");
Console.WriteLine(dirInfo1.Name);
var dirInfo4 = new DirectoryInfo(@"C:\Foo\Bar\");
Console.WriteLine(dirInfo2.Name);

if( dirInfo1.FullName!=dirInfo3.FullName) throw new Exception(@"1-3");
if( dirInfo2.FullName!=dirInfo4.FullName) throw new Exception(@"2-4");
```

In my tests, the `ZlpDirectoryInfo` classes resulted in the same string as those `DirectoryInfo` classes.

**Comment by KimikoMuffin** [comment]
One sec while I try this with the exact path that was causing the issue ...

It seems to have something to do with the length. Or something. I got the effect when I used `D:\SomeStuff\Name Space\More.Stuff\Test`

This is on the latest NuGet release, by the way, 1.0.0.16

**Comment by UweKeim** [comment]
Sorry, my above tests are flawed. I'll can see the different behavior now.

**Comment by UweKeim** [comment]
I've just updated the NuGet package.

(Pushing the changes here To GitHub currently lead to an error, will try again later)
