### ISSUE TITLE
Question: Mono Support

### ISSUE THREAD

**Issue by vector-man** [UweKeim/ZetaLongPaths#16]
Will this library run on Mono too or do I need to distribute a separate version of my application that simply uses the default IO libs for that?

**Comment by UweKeim** [comment]
Since I'm using [P/Invoke](https://en.wikipedia.org/wiki/Platform_Invocation_Services) excessively, I am pretty sure that this will not run under Mono, at least not in a portable way.

**Comment by vector-man** [comment]
Thanks!
