### ISSUE TITLE
ZlpFileInfo OpenRead method throws Pathtoolong exception.

### ISSUE THREAD

**Issue by suresh-dev** [UweKeim/ZetaLongPaths#17]
I am using zeta long paths nuget package with v1.0.0.16 . i am getting path too long exception when i try to read the file. I am able to fetch the files information but unable to read the file.

**Comment by UweKeim** [comment]
That is a very broad error description.

Please read and follow "[**How to Report Bugs Effectively**](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)".

**Comment by UweKeim** [comment]
Since I've got no more detail feedback on this, I'm closing it. Feel free to re-open or post another issue when you have more details to report.

Please read and follow "[**How to Report Bugs Effectively**](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)" _before_ posting again.
