### ISSUE TITLE
Short path name on network paths fails

### ISSUE THREAD

**Issue by mat100payette** [UweKeim/ZetaLongPaths#20]
I have been able to create files on a network path (ex: `\\my.net.foo\some\long\path\bar.txt`) but then I encounter 2 problems:

1. I can't do anything with the file because obviously Explorer can't support it for some reason. So how would I proceed to delete the file?
2. When I try to get a short path name on what it seems to be any network path, even if part of it is mapped to a drive (ex: `Z:\long\path\bar.txt`, where `Z:` is `\\my.net.foo\some`), the returned path is always longer than the original path.

Some additionnal info:

- Windows 8 (On my laptop)
- Works on paths that aren't network ones. I can get short path name for long paths on my desktop for example (`C:\`)

I'm thinking it may have to do with the protocol used for the network file system as described [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364989%28v=vs.85%29.aspx) but other than that I'm clueless. If that truly is the problem (I don't have the info concerning what technology is used yet) then there's not much I can do.

Am I on the right track or am I missing something?

**Comment by UweKeim** [comment]
I'm not sure how this is related to the ZetaLongPaths library.

Can you provide a [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by mat100payette** [comment]
A MVCE is a littlr bit hard to provide since the problem appears only on shared file systems. That being said, I had done some research and I was told that the protocol that the company used did not support short paths.

(I dont have the exact code nearby)
Basically, all I was trying to do was to create a new ZlpFileInfo("\\woah.this.path\is\loooong...") and then open a stream to it so that it would be created on the FS. It did work kinda, as in it created the file on the shared FS, but the short name version of the file would simply not be shorter than its normal name. That's where he protocol thing comes into play I'm fairly sure...

On another note, I notoced that if I create a file on my desktop (not related to shared FS), like "C:/desktop/teeeeeeeeeee...xt.txt" using Zlp (because windows wouldnt let me obviously), then I cant do anything with the file manually. It becomes impossible to open it, delete it, rename it, etc. because windows complains that the filename is too long. Is there a way to avoid such a thing ?

Thank you for your time.
Mat

**Comment by UweKeim** [comment]
Thanks, Mat. I've never experienced the behaviour you describe regarding your desktop files.

I'm using my library for the solely purpose of handling too long _directory_ paths because of the total nested directories add up to more than `MAX_PATH` characters long.

I've never dealt with _single_ components (file name or directory name) of the complete path being more than `MAX_PATH` characters long.

I could imagine that a lot of applications and Windows components do not handle this very well.

**Comment by mat100payette** [comment]
Fair enough ! I personally do not need the help anymore and it doesn't seem to be a common problem.

Have a nice day.
Mat
