### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by anders-eriksson** [UweKeim/ZetaLongPaths#21]
There is a typo in the sample code in the readme

`var folderPath = new ZetaDirectoryInfo( @"C:\My\Long\Folder\Path"` );

**ZetaDirectoryInfo** is not found! but **ZlpDirectoryInfo** is!

Guessing some refactoring has been done ;-)

Thanks for a really nice library!

**Comment by UweKeim** [comment]
Fixed, thank you for finding and mentioning the issue.
