### ISSUE TITLE
ZetaLongPaths can't move files from long source path on Windows Server 2012

### ISSUE THREAD

**Issue by Pawel-Durzynski** [UweKeim/ZetaLongPaths#22]
There is an exception when ZetaLongPaths moves files from long source path on Windows Server 2012. Operating system is up to date. Source path + name of file limit is 256 chars, after this length the problem starts to occur.

**Method:**

    ZlpIOHelper.MoveFile(source, destination);

**Exception:**

> System.ComponentModel.Win32Exception (0x80004005): Error 123 moving file `'\\?\C:\Program Files (x86)\xxxx.txt'` to `'\\?\D:\xxxxx.txt'`: The filename, directory name, or volume label syntax is incorrect.
   at ZetaLongPaths.ZlpIOHelper.MoveFile(String sourceFilePath, String destinationFilePath, Boolean overwriteExisting) in c:\P\ZetaLongPaths\Source\RuntimeNetCore\ZlpIOHelper.cs:line 489

Is there any solution to this problem?

**Comment by UweKeim** [comment]
I've tested on both Windows Server 2012 and Windows Server 2012 R2.

In both cases, I did _not_ succeed in generating the error. Everything worked as expected.

Can you assemble a [MCVE](https://stackoverflow.com/help/mcve) so I can reproduce the error here?

**Comment by arturkula** [comment]
Hi @UweKeim 

Your example works fine on our machines, so I guess that we will rewrite our code to fixed our issue.

But based on our code and yours, here is example of code that is breaking even on windows 10:

`

using System;
using ZetaLongPaths;

namespace ZetaLongPathsTests
{
    internal static class Program
    {
        private static void Main()
        {
            try
            {
                Console.WriteLine();
                Console.WriteLine();

                const string longFileOnC = @"C:\Ablage\test-only\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\LalalaC.txt";

                var f1 = new ZlpFileInfo(longFileOnC);
                f1.Directory.Create();
                f1.WriteAllText("lalala.");
                Console.WriteLine($"f1.FullName.Length: {f1.FullName.Length}");

                const string longFileOnD = @"D:\Ablage\test-only\Ablage2\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\LalalaD.txt";

                var f2 = new ZlpFileInfo(longFileOnD);
                f2.Directory.Create();

                f1.MoveTo(f2, true);
                Console.WriteLine($"f2.FullName.Length: {f2.FullName.Length}");

                Console.WriteLine();
                Console.WriteLine();
                Console.WriteLine("sourceFile:");
                Console.WriteLine(f1.FullName);
                Console.WriteLine();
                Console.WriteLine("destinationFile:");
                Console.WriteLine(f2.FullName);
                ZlpIOHelper.MoveFile(f1.FullName, f2.FullName);
            }
            finally
            {
                Console.WriteLine();

                const string cAblageTestOnly = @"C:\Ablage\test-only\";
                new ZlpDirectoryInfo(cAblageTestOnly).Delete(true);
                Console.WriteLine($"deleted: {cAblageTestOnly}");

                const string dAblageTestOnly = @"D:\Ablage\test-only\";
                new ZlpDirectoryInfo(dAblageTestOnly).Delete(true);
                Console.WriteLine($"deleted: {dAblageTestOnly}");
            }
        }
    }
}

`

**Comment by UweKeim** [comment]
When using your example, the first error I get is "error 2" (file not
found).

This is because of your line "f1.MoveTo(f2, true);" which moves the file
away, and you later on try to move it again, although it was already moved
away.

If I remove the mentioned line, next error is at
"ZlpIOHelper.MoveFile(f1.FullName, f2.FullName)". This is because you do
not specify the third parameter whether to allow overwrite.

When I change the line to "ZlpIOHelper.MoveFile(f1.FullName, f2.FullName,
true)", everything succeeds on my Windows 10.

---

This said, I still am unable to get the initial error code *123* that you
mention in your question.




Am Fr., 24. Aug. 2018 um 10:31 Uhr schrieb Artur Kula <
notifications@github.com>:

**Comment by UweKeim** [comment]
_(currently discussing via email with Pawel; I will post the results here later on)_

**Comment by arturkula** [comment]
Hi @UweKeim 

Found an issue, but can't tell if this is bug or feature. Here you have repro code (notice double \\ in f2 path) :

var f1 = new ZlpFileInfo(
                @"C:\Ablage\test-only\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Lalala.txt");
            f1.Directory.Create();
            f1.WriteAllText("lalala.");
            Console.WriteLine("f1.Length: " + f1.Length);

            var f2 = new ZlpFileInfo(
                @"D:\Ablage\test-only\Ablage2\Ablage\Ablage\Ablage\\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Ablage\Lalala.txt");
            f2.Directory.Create();

            f1.MoveTo(f2, true);
            Console.WriteLine("f2.Length: " + f2.Length);

            new ZlpDirectoryInfo(@"C:\Ablage\test-only\").Delete(true);
            new ZlpDirectoryInfo(@"D:\Ablage\test-only\").Delete(true);

**Comment by arturkula** [comment]
I think it is a bug, when I shorten the f2 path to: D:\Ablage\test-only\Ablage2\Ablage\\Ablage\LalalaD.txt moving file is working fine.

**Comment by Pawel-Durzynski** [comment]
Hello UweKeim,

I can admit that there is a bug with double backslashes reported by email. There is no need to discuss via email :)

Besta regardss,
Pawel

**Comment by UweKeim** [comment]
Sorry, I do not fully understand:

In my examples there are no double-slashes between "Ablage\\Ablage".

How do you want me to fix this?






Am Fr., 24. Aug. 2018 um 13:12 Uhr schrieb Pawel-Durzynski <
notifications@github.com>:

**Comment by arturkula** [comment]
There is some inconsistence:
1. When moving file to destination path that is short and contains `\\` - this works.
2. When moving file to destination path that is long and contains `\\` - this do not work.

I think this should work the same whether path is long or short.
If `\\` is legal in path it should work in short and long path.
If `\\` is illegal in paths it should not work in both short and long paths.

I can't tell how to fix this in code. I managed to fix our internal code to not to generate `\\` in paths.

**Comment by UweKeim** [comment]
Since I'm primarily forwarding my method calls to PInvoke Win32 API calls, and I'm not sure about all the file path formats out there possible, I do not dare to implement logic inside my library.

Instead, I do prefer to let the PInvoke call fail since this is the most accurate checking about whether a path is valid or invalid.

I do hope you understand.
