### ISSUE TITLE
Error 0

### ISSUE THREAD

**Issue by andreweberle** [UweKeim/ZetaLongPaths#23]
First of all, thank you for all your hard work you have put in in making this project.

Getting Error Code 0 when reading a files information eg owner and so on.
I'm thinking it might have something to do with getting these file properties if the file is currently in use?

I have however made a work around by streaming the file first and if it can stream, then that means the file is not locked, however if it cant, it means the file is locked and in use.

Seems to have solved my issue, well for now, however I was wondering if Error 0 is possibly something else?

**Comment by UweKeim** [comment]
Could you provide a [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by andreweberle** [comment]
Certainly can when I'm in the office tomorrow morning, Australian time.

**Comment by UweKeim** [comment]
Since I got no feedback, closing now. Feel free to open again, once you have a MCVE.
