### ISSUE TITLE
Directory.GetFiles return long path file names when path contains tilde character "~"

### ISSUE THREAD

**Issue by E-Mans-Application** [UweKeim/ZetaLongPaths#24]
Hello,

I am experiencing an issue with Zeta Long Paths.
When I want to get the files within a directory which contains the char ~, the name of files it contains starts with "\\\\?\C:\" instead of "C:\" only.

Here is my code:

```
Dim path as String = "C:\path~test"
Dim objFileInfo As ZlpFileInfo
Dim objDir As ZlpDirectoryInfo = New ZlpDirectoryInfo(path)
For Each objFileInfo In objDir.GetFiles()
      MsgBox(objFileInfo.FullName) ' \\?\C:\path~test\my_file
Next
```

I don't have the issue when I use the correct file path to create a ZlpFileInfo object:
`
MsgBox(New ZlpFileInfo(path + "\my_file").FullName) 'C:\path~test\my_file`

**Comment by UweKeim** [comment]
I've figured out that this is intentionally, due to #12. 

To me it is unclear whether I can finde a more reliable way than just checking for tilde `~`.

Suggestions are welcome.
