### ISSUE TITLE
Missing License information in NuGet

### ISSUE THREAD

**Issue by rafalfrukowski** [UweKeim/ZetaLongPaths#26]
It's a good practice to provide license information together with NuGet Package so it is available in nuspec file.

**Comment by UweKeim** [comment]
Can you give an example/link to docs on how do this?

**Comment by rafalfrukowski** [comment]
Here: https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg

**Comment by UweKeim** [comment]
Thanks, I've added a license and just uploaded a new [NuGet package](https://www.nuget.org/packages/ZetaLongPaths).

**Comment by rafalfrukowski** [comment]
I can see that for .NetStandard the license appeared but not for .NetFramework. Could you also add this information there?

**Comment by UweKeim** [comment]
Sorry, I forgot that file. Will add immediately.

**Comment by UweKeim** [comment]
Added in [1.0.0.36](https://www.nuget.org/packages/ZetaLongPaths/1.0.0.36).

**Comment by rafalfrukowski** [comment]
Thank you!
