### ISSUE TITLE
TraceInformation: About to get file length for path, etc.

### ISSUE THREAD

**Issue by rafalfrukowski** [UweKeim/ZetaLongPaths#27]
Hi,
I can see in our logs that we get many logs from your library. It is good to have logs on critical moments but all logs like "About to do ..." are a bit overhead from user perspective. Could those be removed? There are few methods that have that log at the beginning.

**Comment by UweKeim** [comment]
Agree. Changed, committed and submitted to NuGet. 1.0.0.37.

**Comment by rafalfrukowski** [comment]
Is it done for not .Net Framwork and .Net Standard?

**Comment by rafalfrukowski** [comment]
Hi Uwe,
Is it possible that you will also release for NetStandard version as well?

Best regards
Rafał Frukowski

wt., 17 mar 2020 o 09:19 Uwe Keim <notifications@github.com> napisał(a):

**Comment by SergeyFilippov** [comment]
Hi @rafalfrukowski ,

It is considered a good practice in open source world to make changes that you would like to see in project yourself and then send a pull request. 
Also common good practise is to at least say "thank you" for implementation of your requests.

**Comment by rafalfrukowski** [comment]
I'm not that used to open source yet, sorry.
The issue is solved for .Net Framework and I would also like to have it for .Net Standard version.
Thank you very much in front.
