### ISSUE TITLE
Poor performance for GetDirectories/GetFiles

### ISSUE THREAD

**Issue by taori** [UweKeim/ZetaLongPaths#28]
I am using this package in my project at https://github.com/taori/VolumeScanner2/tree/bugfix/performanceoptimization

However after a lot of Performance optimization i came to a point where the hot path are the two methods in the title - Do you think there is any way those methods could be sped up anymore or is it just slow by nature of things?

on a m2ssd scanning 150gb recursively takes 27 seconds. Does that seem reasonable or is there room for more performance?

**Comment by UweKeim** [comment]
Just a wild guess: 

Probably it would be good to not get the whole thing into memory but use something like [`Directory.EnumerateFiles`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles) which iterates file-by-file.

If you would like to contribute to the library, just submit a pull request.

**Comment by taori** [comment]
> 
> 
> Just a wild guess:
> 
> Probably it would be good to not get the whole thing into memory but use something like [`Directory.EnumerateFiles`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles) which iterates file-by-file.
> 
> If you would like to contribute to the library, just submit a pull request.

okay. I'll build from source and have a look which paths are hot. i sure hope it isn't some pinvoke method, because then there would be no way to optimize i guess

**Comment by taori** [comment]
Hm. I can't reference the project because it won't compile because it won't redownload the Microsoft.Net.Compilers.Toolset package - which version of VS are you using?

**Comment by taori** [comment]
Doesnt look like this can be fixed without substantial effort.

![grafik](https://user-images.githubusercontent.com/5545184/77228946-095df480-6b8b-11ea-825e-df59dacd26b3.png)

At least not without substentially refactoring the underlying call hierarchy.

**Comment by UweKeim** [comment]
Maybe use some if/else to check whether a path is a long/short path and fall back to the .net Framework functions for these cases?  (Assuming that those are faster)
