### ISSUE TITLE
ZetaLongPaths.ZlpFileInfo(_Path).OpenRead() not work on windows 8.1

### ISSUE THREAD

**Issue by MustafaDaoud90** [UweKeim/ZetaLongPaths#31]
string _Path = "LongPath";
System.IO.FileStream oReader = ZetaLongPaths.ZlpFileInfo(_Path).OpenRead();
not work on windows 8.1 almost return 0 bytes when read and when call windows error after this line return error (183) meaning: 
ERROR_ALREADY_EXISTS
183 (0xB7)
Cannot create a file when that file already exists.

Note: the writer works fine on the same long path.

the same code works fine on the short path.

what is the problem?

**Comment by UweKeim** [comment]
`ERROR_ALREADY_EXISTS` usually indicates a permission issue (not enough permissions because of ACL and/or write-protection flag).

**Comment by MustafaDaoud90** [comment]
I set full control permissions for the file but the same problem returned!!!

                System.IO.FileStream oReader = new ZetaLongPaths.ZlpFileInfo(txtPath.Text).OpenRead();
                int error = System.Runtime.InteropServices.Marshal.GetLastWin32Error();
                using (oReader)
                {
                    byte[] buffer = new byte[65536];
                    int read = 0;
                    while (true)
                    {
                        read = oReader.Read(buffer, 0, buffer.Length);
                        int error1 = System.Runtime.InteropServices.Marshal.GetLastWin32Error();
                        if (read <= 0)
                                break;
                            //backupFileStream.Write(buffer, 0, read);
                    }
                }
                oReader.Close();


almost return read = 0 when read from reader.

**Comment by MustafaDaoud90** [comment]
Thank you, worked.
