### ISSUE TITLE
IsPathRooted

### ISSUE THREAD

**Issue by MustafaDaoud90** [UweKeim/ZetaLongPaths#32]
How to get IsPathRooted in ZetaLongPath?
such as System.IO.Path.IsPathRooted(_path) return boolean true or false.

**Comment by UweKeim** [comment]
Would [the method `ZlpPathHelper.IsAbsolutePath()`](https://github.com/UweKeim/ZetaLongPaths/blob/49052caeec83416a3cbdae28f5c7fcf0e39ca676/Source/Runtime/ZlpPathHelper.cs#L953) be of any help?

**Comment by MustafaDaoud90** [comment]
yes, it helps me.

Thank you a lot.
