### ISSUE TITLE
GetDirectoryRoot(_path)

### ISSUE THREAD

**Issue by MustafaDaoud90** [UweKeim/ZetaLongPaths#33]
How to get GetDirectoryRoot() in ZetaLongPath?
such as [System.IO.Directory.GetDirectoryRoot(_path)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getdirectoryroot)

**Comment by UweKeim** [comment]
Could you check whether [`ZlpPathHelper.GetDriveOrShare()`](https://github.com/UweKeim/ZetaLongPaths/blob/master/Source/Runtime/ZlpPathHelper.cs#L707) might help?

Alternatively, [`ZlpPathHelper.GetDriveOrShareAndDirectory()`](https://github.com/UweKeim/ZetaLongPaths/blob/master/Source/Runtime/ZlpPathHelper.cs#L735) might also help.

**Comment by MustafaDaoud90** [comment]
yes, it helps me.

Thank you a lot.
