### ISSUE TITLE
Question about IZlpFileSystemInfo

### ISSUE THREAD

**Issue by MustafaDaoud90** [UweKeim/ZetaLongPaths#34]
I need to know if the IZlpFileSystemInfo same as System.IO.FileSystemInfo?

When using in System.IO
FileSystemInfo BLFileInf = (FileSystemInfo)(new FileInfo(sBlockFile));
in zeta
IZlpFileSystemInfo BLFileInf = (IZlpFileSystemInfo)(new ZlpFileInfo(sBlockFile));
above is same?!

**Comment by UweKeim** [comment]
It is _technically_ not the same but should be same enough for most of the use cases.

So my assumption is that the answer is: "**Yes**" 😊

**Comment by MustafaDaoud90** [comment]
Thanks a lot for the fast reply,

in System.IO.FileSystemInfo contain Refresh() method, I need to use it but in IZlpFileSystemInfo not found what is the alternative to use?

**Comment by UweKeim** [comment]
I'll add the `Refresh` to the interface.

In contrast to the original `System.IO` classes, my classes do _not_ cache values.  So the `Refresh()` is merely to be similar to the original classes, but it does _not_ have an actual implementation as of now. You could simply omit calling it at all.
