### ISSUE TITLE
Check to ZlpFileInfo.Exists inaccurately shows "TRUE"

### ISSUE THREAD

**Issue by msbair** [UweKeim/ZetaLongPaths#37]
We have a process that checks whether a file exists or not and does something based on this check. The ZlpFileInfo inaccurately states the file exists when it does not:

`\\{LONG_NETWORK_PATH\~$HIDDEN_EXCEL_FILE_LOCK.xlsm`

For example:

`\\xyz.com\dfsroot-us\shared\G\PMOutput\Mont\F\~$F_vPrd.xlsm`

**Comment by UweKeim** [comment]
I've just did a quick test:

```c#
var a = new ZlpFileInfo(@"\\nas001\data\Users\ukeim\Ablage\F~$F_vPrd.xlsm");
var exists = a.Exists;

Assert.IsFalse(exists);
```

This assertion did _not_ fire. I.e. `exists` is "false", just as I would expect.

So while this might still be an issue in the library, as of now I cannot reproduce it.

Could you please assemble a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by msbair** [comment]
![Capture](https://user-images.githubusercontent.com/32419278/135879321-97c9f29a-e51d-4b5f-92bd-411a4c46187a.PNG)

![Capture2](https://user-images.githubusercontent.com/32419278/135879582-baafaccf-9781-4a11-87b2-d6012d41ca93.PNG)

I wonder if it has to do with it being on a network share?

I'll try and create a reproducible example.

**Comment by Smurf-IV** [comment]
?? network share might have "Cacheable" items on, so returns true until actual existence is tested via an open.

**Comment by msbair** [comment]
It works as expected on local drive.

**Comment by msbair** [comment]
System.IO.FileInfo functions the same as ZlpFileInfo.
