### ISSUE TITLE
Latest package version v1.0.9.41 has dependency to JetBrains.Annotations v1.0.0

### ISSUE THREAD

**Issue by Lorilatschki** [UweKeim/ZetaLongPaths#38]
The latest package has a Dependency to `JetBrains.Annotations 1.0.0` which leads to a compiler warning:

> warning NU1603: ZetaLongPaths 1.0.9.41 depends on JetBrains.Annotations (>= 1.0.0) but JetBrains.Annotations 1.0.0 was not found. An approximate best match of JetBrains.Annotations 6.1.0 was resolved.

```xml
...
<dependencies>
  <dependency id="JetBrains.Annotations" version="1.0.0" />
</dependencies>
...
```

On https://www.nuget.org/packages/JetBrains.Annotations there is no matching version. Can you please remove this dependency since it is not required as a runtime dependency?

**Comment by trycache0905** [comment]
您好！    您的邮件已收到，我会尽快处理！谢谢！    顺祝：工作顺利！

**Comment by UweKeim** [comment]
Sounds reasonable. 

I guess, I could add it as a [development dependency](https://docs.microsoft.com/en-us/nuget/reference/nuspec#developmentdependency)? Or would you recommend to completely remove it?

**Comment by Lorilatschki** [comment]
In version 1.0.7.41 it was not part of the nuspec file at all. So I would recommend to completely remove it. 

Any idea why this was added to the nuspec?

**Comment by UweKeim** [comment]
OK, thanks.

I've added it, because I did think it was necessary, not understanding that the compiler/linker would probably remove all references to this library upon compilation.

A new [version 1.0.10.41](https://www.nuget.org/packages/ZetaLongPaths/1.0.10.41) was just published to NuGet.

**Comment by Lorilatschki** [comment]
Great! Thanks for the quick fix!
