### ISSUE TITLE
ZlpPath.Combine

### ISSUE THREAD

**Issue by MustafaDaoud90** [UweKeim/ZetaLongPaths#39]
When use ZlpPathHelper.Combine(path1, path2) function not return the same as System.IO.Path.Combine(path1, path2).

For example when use  System.IO.Path.Combine(path1, path2):

System.IO.Path.Combine("C:\\Users\\m.ahmad\\AppData\\Roaming\\MustafaDaoud\\MustafaDaoud\\Jobs\\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\\Data\\BackupCache\\","C:\\Users\\m.ahmad\\AppData\\Roaming\\MustafaDaoud\\MustafaDaoud\\Jobs\\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\\Data\\BackupCache\\9219909703685094454.pst")

returns this path:
C:\Users\m.ahmad\AppData\Roaming\MustafaDaoud\MustafaDaoud\Jobs\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\Data\BackupCache\3948766359955674179.pst

but when use ZlpPathHelper.Combine(path1, path2):

ZlpPathHelper.Combine("C:\\Users\\m.ahmad\\AppData\\Roaming\\MustafaDaoud\\MustafaDaoud\\Jobs\\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\\Data\\BackupCache\\","C:\\Users\\m.ahmad\\AppData\\Roaming\\MustafaDaoud\\MustafaDaoud\\Jobs\\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\\Data\\BackupCache\\9219909703685094454.pst")

returns this path:
C:\Users\m.ahmad\AppData\Roaming\MustafaDaoud\MustafaDaoud\Jobs\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\Data\BackupCache\C:\Users\m.ahmad\AppData\Roaming\MustafaDaoud\MustafaDaoud\Jobs\{6E820F39-1F0F-4C22-A9F6-5E7CAE6F6FA7}\Data\BackupCache\3948766359955674179.pst

please advise.

**Comment by UweKeim** [comment]
What would be the reason to combine two _absolute_ paths?

**Comment by trycache0905** [comment]
您好！    您的邮件已收到，我会尽快处理！谢谢！    顺祝：工作顺利！

**Comment by MustafaDaoud90** [comment]
because I want to use it in my project to accept long path and I replace my code from using System.IO.Path to ZlpPathHelper without changing the original code structure, if you can help me.

Thanks for the quick reply.

**Comment by UweKeim** [comment]
Still, no matter which library, what is the logical reason to combine two _absolute_ paths?

**Comment by MustafaDaoud90** [comment]
I need the complete path details to create a new file, starting from the root element and ending with the other subdirectories.

**Comment by MustafaDaoud90** [comment]
Please I need it urgently, if can you help me.

**Comment by UweKeim** [comment]
I do think I have a fix.

Will add more unit tests and release an update later to NuGet.

**Comment by MustafaDaoud90** [comment]
Thanks a lot boss, now I can to download updated package from NuGet
