### ISSUE TITLE
Tilde problem

### ISSUE THREAD

**Issue by MustafaDaoud90** [UweKeim/ZetaLongPaths#41]
windows convert the long path to a short path using Tilde "~" for example:

return from windows:
C:\HOTLON~1\TESTLO~1\NEWFOL~1\MAAAAA~1\ROOOOO~1\ALLLLL~1\QAAAAA~1\ORIGIN~1\TESTTT~1\test221\HOTLON~1.PNG

the original path:
C:\HOTLongPathTEST\TestLongPathhhhhhh211\Newfolder11\Maaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaain11\Roooooooooooooooooooooooooooooooooooooooooooooooot11\ALLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL11\QAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrrrrrrrrrrrrtttttttttttttttttttttttttttttttttttt11\originallllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll11\testttt111\test221\HotLongtest.png

when pass the windows return path to the zeta file info and check if zlpFileInfo.Exists or not always returns Exists = False and zlpFileInfo.FullName returns the short path as windows.

![image](https://user-images.githubusercontent.com/85986087/174009342-2bea8e6e-4e15-4230-8793-b33b7534b9df.png)

**Comment by UweKeim** [comment]
Currently, I do have no interest and intention to support short paths.

Feel free to add this functionality by yourself and send a pull request.
