### ISSUE TITLE
ZetaLongPaths.ZlpIOHelper.MoveDirectory fails inside the same directory

### ISSUE THREAD

**Issue by patpowerman** [UweKeim/ZetaLongPaths#5]
If you try to move an entire SubDirectory one ore more levels up inside the same Directory, you get an error like 

    "can't be moved if directory already exists..."

Example:

> SourceDir = C:\temp\SourceDir\SubDir1\SubDir2\SubDir3 (with various files.xxx inside)
> TargetDir = C:\temp\SourceDir

Attempt to move the \SubDir3 (with entire content) to \SourceDir
ZetaLongPaths.ZlpIOHelper.MoveDirectory(SourceDir , TargetDir)

Why should it not be possibe to `.MoveDirectory` inside the same directory structure?

**Comment by xmenxwk** [comment]
It is possible, its probably the condition check that is not recognizing correctly. You should look inside the source, and post a pull request ?

**Comment by UweKeim** [comment]
Never heard back from original reporter. Therefore closing.
