### ISSUE TITLE
Project is lacking license information

### ISSUE THREAD

**Issue by VictorBlomberg** [UweKeim/ZetaLongPaths#7]
Hi,

Is this software licensed under an FLOSS/[Open Source](http://opensource.org/licenses) license? Would it, in that case, be possible to include a LICENSE file in the root of the repository?

The project seems really great, but using software without a stated license is way too dangerous for me.

Victor Blomberg

**Comment by UweKeim** [comment]
Sorry, I'm no licensing expert. Is "Do whatever you want, pay nothing, give credit or not, I don't care". enough for you?

**Comment by UweKeim** [comment]
I've just added the MIT license inside a LICENSE.txt as copied from http://choosealicense.com/licenses/mit/ - Is this OK for you?

**Comment by VictorBlomberg** [comment]
Hi! Thank you, that is perfect!
