### ISSUE TITLE
GetFileNameWithoutExtension return empty string on filename with no extension

### ISSUE THREAD

**Issue by mircoboschi** [UweKeim/ZetaLongPaths#9]
When calling `ZlpPathHelper.GetFileNameWithoutExtension` with a filename without extension,
the function is returning an empty string.

The correct return value should be the whole filename, as it doesn't contain extension.

**Comment by UweKeim** [comment]
@mircoboschi I've just added a bunch of unit tests. I cannot confirm your experience.

Can you give me an example on how I can see the misbehaviour, too?

Here are my additional tests:

	s1 = @"c:\folder1\folder2\folder3\file1.txt";

	s3 = ZlpPathHelper.GetFileNameFromFilePath(s1);
	s4 = Path.GetFileName(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"c:\folder1\folder2\folder3\file1";

	s3 = ZlpPathHelper.GetFileNameFromFilePath(s1);
	s4 = Path.GetFileName(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"c:\folder1\folder2\folder3\file1.";

	s3 = ZlpPathHelper.GetFileNameFromFilePath(s1);
	s4 = Path.GetFileName(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"file1.txt";

	s3 = ZlpPathHelper.GetFileNameFromFilePath(s1);
	s4 = Path.GetFileName(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"file1";

	s3 = ZlpPathHelper.GetFileNameFromFilePath(s1);
	s4 = Path.GetFileName(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"file1.";

	s3 = ZlpPathHelper.GetFileNameFromFilePath(s1);
	s4 = Path.GetFileName(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"c:\folder1\folder2\folder3\file1.txt";

	s3 = ZlpPathHelper.GetFileNameWithoutExtension(s1);
	s4 = Path.GetFileNameWithoutExtension(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"c:\folder1\folder2\folder3\file1";

	s3 = ZlpPathHelper.GetFileNameWithoutExtension(s1);
	s4 = Path.GetFileNameWithoutExtension(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"c:\folder1\folder2\folder3\file1.";

	s3 = ZlpPathHelper.GetFileNameWithoutExtension(s1);
	s4 = Path.GetFileNameWithoutExtension(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"file1.txt";

	s3 = ZlpPathHelper.GetFileNameWithoutExtension(s1);
	s4 = Path.GetFileNameWithoutExtension(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"file1";

	s3 = ZlpPathHelper.GetFileNameWithoutExtension(s1);
	s4 = Path.GetFileNameWithoutExtension(s1);

	Assert.AreEqual(s3, s4);

	// --

	s1 = @"file1.";

	s3 = ZlpPathHelper.GetFileNameWithoutExtension(s1);
	s4 = Path.GetFileNameWithoutExtension(s1);

	Assert.AreEqual(s3, s4);

**Comment by mircoboschi** [comment]
Here is an example call:
GetFileNameWithoutExtension(@"\\?\C:\Simulazioni\Albero\scratch_file");
This call returns an empty string.

**Comment by mircoboschi** [comment]
![1](https://cloud.githubusercontent.com/assets/11681306/10072932/7e22604a-62c5-11e5-9972-e86f4e813b0a.PNG)
![2](https://cloud.githubusercontent.com/assets/11681306/10072933/7e246d36-62c5-11e5-9601-326bafc5490a.PNG)

**Comment by UweKeim** [comment]
Sorry, I've tried again and still cannot confirm.

These three tests succeed:

	var r = ZlpPathHelper.GetFileNameWithoutExtension(@"\\?\C:\Simulazioni\Albero\scratch_file.txt");
	Assert.AreEqual(r, @"scratch_file");

	r = ZlpPathHelper.GetFileNameWithoutExtension(@"\\?\C:\Simulazioni\Albero\scratch_file.");
	Assert.AreEqual(r, @"scratch_file");

	r = ZlpPathHelper.GetFileNameWithoutExtension(@"\\?\C:\Simulazioni\Albero\scratch_file");
	Assert.AreEqual(r, @"scratch_file");

**Comment by mircoboschi** [comment]
I've found that i was running 1.0.0.6 version, that seems to expose this behaviour.
Updating the library to 1.0.0.8 seems to fix the issue.
